spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
<<<<<<< HEAD
  properties:
    hibernate:
#     show_sql: true
      format_sql: true
=======
    properties:
      hibernate:
  #     show_sql: true
        format_sql: true
>>>>>>> e8d7ca10d5be7b00d94cf4b615b5199542d8bd70
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace